# Generated by Django 5.1.7 on 2025-10-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0011_alter_problem_testcases_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='contest_letter',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
